version: '3.8'

services:
  backend:
    build:
      context: ./FoodVerse-backend
      dockerfile: Dockerfile
    volumes:
      - ./foodverse-backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=debug
    depends_on:
      - db
    networks:
      - foodverse-net

  frontend:
    build:
      context: /FoodVerse-frontend
      dockerfile: Dockerfile
    volumes:
      - ./foodverse-frontend:/app
      - /app/node_modules
    working_dir: /app
    command: "npm run dev"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USERPOOLING=true
    networks:
      - foodverse-net

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foodverse
      POSTGRES_PASSWORD: foodverse
      POSTGRES_DB: foodverse
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodverse-net

volumes:
  pgdata:

networks:
  foodverse-net: