version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foodverse
      POSTGRES_PASSWORD: foodverse
      POSTGRES_DB: foodverse
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodverse-net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@foodverse.com
      PGADMIN_DEFAULT_PASSWORD: foodverse
    depends_on:
      - db
    networks:
      - foodverse-net

volumes:
  pgdata:

networks:
  foodverse-net:
