version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foodverse
      POSTGRES_PASSWORD: foodverse
      POSTGRES_DB: foodverse
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - foodverse-net

volumes:
  pgdata:

networks:
  foodverse-net: